# Generated by Django 5.2.2 on 2025-06-27 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_detalle_v_options_alter_venta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detalle_v',
            table='detalle_venta',
        ),
    ]
