# Generated by Django 5.2.2 on 2025-06-27 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_v',
            options={'verbose_name': 'detalle_ventas', 'verbose_name_plural': 'detalle_ventas'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'venta', 'verbose_name_plural': 'ventas'},
        ),
        migrations.AlterModelTable(
            name='detalle_v',
            table='veventa',
        ),
        migrations.AlterModelTable(
            name='venta',
            table='venta',
        ),
    ]
