# Generated by Django 5.2.2 on 2025-06-25 02:11

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('rol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('permisos', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='rol')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('documento', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50, null=True)),
                ('apellidos', models.CharField(max_length=50, null=True)),
                ('fecha_nacimiento', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre_completo')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.gestion')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuarios',
            },
        ),
    ]
