# Generated by Django 5.2.2 on 2025-06-06 18:37

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='rol'),
        ),
    ]
