# Generated by Django 5.2.2 on 2025-06-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contraseña',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
