# Generated by Django 5.2.2 on 2025-06-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_user_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
    ]
