# Generated by Django 5.2.2 on 2025-07-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_user_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='rol',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Admin', 'Admin')], max_length=20, primary_key=True, serialize=False),
        ),
    ]
