# Generated by Django 5.2.2 on 2025-09-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_users_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='rol',
            field=models.CharField(choices=[('cliente', 'cliente'), ('admin', 'admin')], max_length=20, primary_key=True, serialize=False),
        ),
    ]
