# Generated by Django 5.2.2 on 2025-07-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_productos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='foto',
            field=models.ImageField(null=True, upload_to='uploads/productos/'),
        ),
    ]
