# Generated by Django 5.2.2 on 2025-08-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_productos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
