# Generated by Django 5.2.2 on 2025-06-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/productos/'),
        ),
    ]
