# Generated by Django 5.2.2 on 2025-07-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_productos_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='estado',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
