# Generated by Django 5.2.2 on 2025-08-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_productos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
