# Generated by Django 5.2.2 on 2025-06-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_user_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contraseña',
            field=models.CharField(max_length=100),
        ),
    ]
