# Generated by Django 5.2.2 on 2025-07-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_gestion_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=100),
        ),
    ]
