# Generated by Django 5.2.2 on 2025-07-31 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_user_estado'),
        ('ventas', '0003_alter_detalle_v_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
