# Generated by Django 5.2.2 on 2025-09-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_rename_user_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Inactivo', max_length=100),
        ),
    ]
