# Generated by Django 5.2.2 on 2025-09-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_gestion_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='fecha_nacimiento',
        ),
    ]
