# Generated by Django 5.2.2 on 2025-09-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetadatau',
            name='expiracion',
            field=models.DateTimeField(null=True),
        ),
    ]
